### ISSUE TITLE
SecureConnector defaults to TLSv1.0 only

### ISSUE THREAD

**Issue by kelunik** [reactphp/socket#101]
`tls://` means only TLSv1.0 in PHP currently, see https://github.com/php/php-src/pull/2518.

**Comment by kelunik** [comment]
Nevermind.

**Comment by clue** [comment]
For the reference: The `tls://` scheme will be removed and processed internally, so that this library actually supports all TLS versions.

See also #107 for a follow-up issue which discusses being able to explicitly only enable certain TLS versions.
