### ISSUE TITLE
A way to manually specify encryption method

### ISSUE THREAD

**Issue by nick4fake** [reactphp/socket#107]
I think it would be great to allow specifying method for StreamEncryption. Fix should be trivial, I'll file MR if this is something you would like to see in this lib

**Comment by nick4fake** [comment]
Just some background: as usual, on old PHP versions (like 5.5.17) socket security works incorrectly - relevant constants were added in PHP 5.6 + it incorrectly handles situations, like forced TLS1.2 on server (with 1.0 and 1.1 disabled)

**Comment by clue** [comment]
Yes, please :+1: 

I wonder what kind of API you have in mind, as this applies to both client- and server-side TLS sockets.

**Comment by clue** [comment]
Ping @nick4fake, what is the status here? :shipit:
