### ISSUE TITLE
[React/Socket/Server]: Can not create socket server #43

### ISSUE THREAD

**Issue by karborator** [reactphp/socket#119]
I'm using Fedora 26 with turned off selinux

When I try to create new instance of
new \React\Socket\Server( "127.0.0.1:5555", $loop);

[RuntimeException]
Failed to listen on "tcp://127.0.0.1:5555": Address already in use

$ sudo lsof -i tcp:5555
$

**Comment by clue** [comment]
Thanks for reporting! Have you tried using another IP/port combination?

You should be able to reproduce this easily as this component basically executes this function under the hood:

```bash
$ php -r "stream_socket_server('tcp://127.0.0.1:5555');"
```

**Comment by karborator** [comment]
$ php -r "stream_socket_server('tcp://127.0.0.1:5555');"
$

**Comment by clue** [comment]
Thanks for reporting that the underlying function works just fine. Can you provide a gist to reproduce the issue you're seeing? It looks like maybe your code is trying to start multiple sockets listening on the same address.

**Comment by karborator** [comment]
Yea I was doing it wrong binding zmq context before that on same ip/port
