### ISSUE TITLE
Test failures on Mac OS X

### ISSUE THREAD

**Issue by andig** [reactphp/socket#121]
Not really an issue, more fyi:

	There were 3 failures:

	1) React\Tests\Socket\FunctionalSecureServerTest::testEmitsErrorIfConnectionIsCancelled
	Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
	Method was expected to be called 1 times, actually called 0 times.

	2) React\Tests\Socket\FunctionalTcpServerTest::testEmitsConnectionEvenIfConnectionIsCancelled
	Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
	Method was expected to be called 1 times, actually called 0 times.

	3) React\Tests\Socket\UnixConnectorTest::testValid
	Failed asserting that Binary String: 0x756e69783a2f2f000000000000000000000000000000 is null.

	/Users/andig/Documents/htdocs/react-socket/tests/UnixConnectorTest.php:62

**Comment by clue** [comment]
Thanks for reporting! Can anybody with Mac OS X confirm these issues? Also, PRs would be welcome! :shipit:

**Comment by WyriHaximus** [comment]
@clue travis supports running the tests on OS X, but IIRC it's a bit of work to get it working: https://docs.travis-ci.com/user/reference/osx/

**Comment by andig** [comment]
I've tested this on OSX

**Comment by jsor** [comment]
I can confirm (latest master including #123):

```
1) React\Tests\Socket\FunctionalSecureServerTest::testEmitsErrorIfConnectionIsCancelled
Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

2) React\Tests\Socket\FunctionalTcpServerTest::testEmitsConnectionEvenIfConnectionIsCancelled
Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
````

**Comment by andig** [comment]
1) only fails sometimes (OSX HighSierra)
2) only fails sometimes (OSX HighSierra)
3) is fixed by https://github.com/reactphp/socket/pull/123

**Comment by andig** [comment]
I've checked if the underlying stream may be the culprit and found https://github.com/reactphp/stream/issues/111 but it seems unrelated.

**Comment by WyriHaximus** [comment]
@andig does it still fail sometimes within the same run when using `--repeat 100` with phpunit

**Comment by andig** [comment]
After failing once the tests get stuck for good on my slowish machine:

	❯ phpunit --repeat 100 tests/TcpConnectorTest.php
	PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

	..........I...........I...........I...........I...........I..   61 / 1200 (  5%)
	.........I...........I...........I...........I...........I...  122 / 1200 ( 10%)
	........I...........I...........I...........I...........I....  183 / 1200 ( 15%)
	.......I...........I...........I...........I...........I.....  244 / 1200 ( 20%)
	E.....I.

or 

	❯ phpunit --repeat 100 tests/TcpConnectorTest.php
	PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

	..........I...........I...........I...........I...........I..   61 / 1200 (  5%)
	.........I...........I...........I...........I...........I...  122 / 1200 ( 10%)
	........I...........I...........I...........I...........I....  183 / 1200 ( 15%)
	.......I...........I...........I...........I...........I.....  244 / 1200 ( 20%)
	......I...........I...........I...........I....EE.....I.

**Comment by clue** [comment]
For the reference: Can anybody run the test suite on Windows and confirm that this is a Mac issue only?

**Comment by WyriHaximus** [comment]
@clue on windows it hangs on `TcpConnectorTest::connectionToEmptyPortShouldFail'`
