### ISSUE TITLE
Support half-open connections (FIN)

### ISSUE THREAD

**Issue by clue** [reactphp/socket#126]
This is particularly useful for some TCP/IP-based protocols where the client sends a FIN message to the server indicating that it will no longer write any data but is still willing to accept incoming data.

Opening this ticket as a reminder and to spark the discussion - the implementation likely depends on  https://github.com/reactphp/stream/issues/27

**Comment by pronskiy** [comment]
Hi guys!
I started to work on this. While still not sure if I can finish, I think I got some results by changing `React\Stream\WritableResourceStream::close()` and replacing lines:
```
 if (is_resource($this->stream)) {
    fclose($this->stream);
}
```
with
```
@stream_socket_shutdown($this->stream, 1);
stream_set_blocking($this->stream, false);
```
i.e. keeping it readable in `DuplexResourceStream`.

Do you think this is a reasonable direction?

**Comment by clue** [comment]
@pronskiy Thank you for looking into this! Sounds like this makes perfect sense on a lower level. This will likely cause a number of tests to fail, but this can probably shouldn't be too much work either. But I'm really curious how this could be exposed API-wise. Have you looked into this yet?

**Comment by pronskiy** [comment]
@clue I plan to submit some draft for your consideration so that we have a basis for discussion.

**Comment by pronskiy** [comment]
@clue here are couple PRs with an early draft. Basically, I add `$options` array as a parameter to various classes' costructor. It's kinda bad because the same array is passed from one class to another. I'm thinking of how to improve it. What do you think of such direction?

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I suppose we would be happy to accept PRs in case anybody feels there's a need for this :+1:
