### ISSUE TITLE
question regarding write function

### ISSUE THREAD

**Issue by evilmake** [reactphp/socket#135]
Hello,
Just a question, using the function $connection->write($data); is it blocking or sync?
I mean if i have to write 10000 times on a connection and one of these times it takes a while for some reasons, will it delay all the other writings or looping the write function and then $loop->run(); , everything starts as unique thread?

Thanks

**Comment by clue** [comment]
The `write()` method is guaranteed to be non-blocking.

The `ConnectionInterface` implements the `DuplexStreamInterface` which implements the `WritableStreamInterface`. This should already be covered in the README and would link you to this: https://reactphp.org/stream/#write

I hope this helps :+1:
