### ISSUE TITLE
Composer on master

### ISSUE THREAD

**Issue by mmoreram** [reactphp/socket#137]
How can we pass tests on master?
composer update on master is not working right  now :(

**Comment by andig** [comment]
Check travis.yml for how to. 

Viele Grüße,
Andreas

**Comment by clue** [comment]
See also https://github.com/reactphp/socket#tests:

```bash
$ COMPOSER_ROOT_VERSION=`git describe --abbrev=0` composer install
```

I hope this helps :+1:

**Comment by mmoreram** [comment]
Thanks @clue :)
