### ISSUE TITLE
Question: How to connect by javascript to the server via sockets

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/socket#142]
Hello, I am trying to make a client server connection via sockets, the server being in reatchphp with the following code.

`<?php

require 'vendor/autoload.php';

$colours = ['red', 'green', 'yellow', 'blue', 'purple', 'cyan'];

$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);

// This event triggers every time a new connection comes in
$socket->on('connection', function ($conn) use ($colours) {
    $colour = array_pop($colours); // Only doing this as an example, you will run out of colours.

    // Event listener for incoming data
    $conn->on('data', function ($data, $conn) use ($colour) {

        // Write data back to the connection

        $conn->write("a");
        $address = $conn->getRemoteAddress();
        echo 'Connection with ' . $address . PHP_EOL;
        // Echo the data into our terminal window
        echo (new \Malenki\Ansi($data))->fg($colour);
    });
});

// Listen on port 1337
$socket->listen(1337);

$loop->run();
`

And the client in javascript with the following code

`var conn = new WebSocket('ws://localhost:1337');
conn.onopen = function(e) {
    console.log("Connection established!");
};

conn.onmessage = function(e) {
    console.log(e.data);
};`

The question is that I managed to connect listening from the console with telnet but with javascript I could not give me the following error

Firefox can not establish a connection to the server at ws: // localhost: 1337 /.

**Comment by clue** [comment]
It looks like you're running a plaintext TCP/IP socket server and are trying to use the WebSocket protocol to connect to this server?

You can use any plaintext TCP/IP client to connect to your server, such as telnet or any other TCP/IP library.

If you want to use a WebSocket client, such as the one provided by your browser, you will have to use a WebSocket server. [Ratchet](https://github.com/ratchetphp/Ratchet) is a WebSocket server that builds on top of this project.

I hope this helps :+1:

**Comment by Juanperezc** [comment]
Hi, I ended up using ratchet and found the solution to my problem, thanks :)
