### ISSUE TITLE
ari tcp connector object not resolving being vpn. manual dns necessary

### ISSUE THREAD

**Issue by hemantjp** [reactphp/socket#144]
Hi.
i have to connect to a vpn as asterisk 2.10 is behind it.
the promise to the connector does not resolve.
```
require '../vendor/autoload.php';
use React\Socket\ConnectionInterface;

$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop);
//$dns = $dnsResolverFactory->createCached('10.10.30.21', $loop);

$connector
    ->connect('pbx-stg.**.com:5038')
    ->then(
        function (ConnectionInterface $conn)  {
            echo "Connection established\n";
        },
        function (Exception $exception) use ($loop){
            echo "Cannot connect to server: " . $exception->getMessage();
            $loop->stop();
        });

$loop->run();
```
there is a dns issue.
i have to hard code the dns.

```
$connector = new React\Socket\Connector($loop,array(
    'dns' => '10.10.30.21'
));
```

what am i doing wrong.
i am able to use the Ratchet Websocket library to make connection to ARI.
there the dns is automatically resolved. i read the source[https://github.com/ratchetphp/Pawl/blob/master/src/Connector.php] but was unable to understand how it is handled effectively.

any tips to resolve this would be wonderful 

Thank You.

**Comment by kelunik** [comment]
I guess this defaults to 8.8.8.8 as DNS server. ReactPHP doesn't respect the system config, yet.

**Comment by clue** [comment]
> there is a dns issue.
i have to hard code the dns.

Thanks for reporting! What issue are you running into? Are you seeing any error output?

Note that this component is currently hard coded to default to use Google's public DNS 8.8.8.8, see https://github.com/reactphp/socket/issues/90. Does explicitly using another DNS server (such as one provided by your provider) solve this issue for you?

**Comment by hemantjp** [comment]
Thank you sir,
There is no specific error. It is just that the promise does not resolve and times out.
i use the terminal to get dns details and am hardcoding it for now.

i will refer to the issue you have attached.

Any thoughts on how the ratchet Websocket library is handling this issue, because it also is using the same connect object?

**Comment by clue** [comment]
> There is no specific error. It is just that the promise does not resolve and times out.

I'm not sure I follow. It's my understanding that your above code should result in a rejected promise, so that you should see error output after the socket connector times out.

Either way, I'm happy to hear that passing an explicit DNS server resolves this for you! Pawl offers a way to inject a `Connector`, so this should work as well: https://github.com/ratchetphp/Pawl#example

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
