### ISSUE TITLE
How to send a command to the server?

### ISSUE THREAD

**Issue by wolrd** [reactphp/socket#154]
I start the server. I want send commands to this server - curl 127.0.0.1:8081/?command=store. 
How can I do it?
```
$loop = \React\EventLoop\Factory::create();
$socket = new \React\Socket\Server('127.0.0.1:8081', $loop);
$socket = new \React\Socket\LimitingServer($socket, null);
$socket->on('connection', function(\React\Socket\ConnectionInterface $connection) use ($socket){
       $connection->on('data', function($data) use ($connection, $socket){
         /*if(command == 'store')
               foreach ($socket->getConnections() as $connection) {
	        $connection->write('store');
	       }
         */
          
       });		
});

$loop->run();
```

**Comment by kelunik** [comment]
You probably want to have a look at https://github.com/reactphp/http instead of the `socket` component directly.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by wolrd** [comment]
@kelunik  I tried using reactphp/https. But I did not understand how to connect to the existing server. How do I connect to the existing server?

```
$loop = \React\EventLoop\Factory::create();
$socket = new \React\Socket\Server('127.0.0.1:8081', $loop);
$server = new \React\Http\Server([$this, 'onHttpRequest']);
$server->listen($socket);
```

**Comment by clue** [comment]
@wolrd Have you seen https://github.com/reactphp/http#quickstart-example and https://github.com/reactphp/http/tree/master/examples ? This is usually a good starting point to get an idea about how this can be used.

**Comment by wolrd** [comment]
@clue yes.   I run 2 scripts and get an error:
Failed to listen on "tcp://127.0.0.1:8081": Address already in use
I did not understand how to connect to the existing server.

**Comment by wolrd** [comment]
I have some workres with EventLoop. I need to send them commands.

**Comment by clue** [comment]
I'm not sure I follow what you're trying to achieve, it sounds like you want to send a "command"(?) to your existing server? What kind of protocol are you using here?

If you're using HTTP, you may want to look into using https://github.com/reactphp/http-client/blob/master/examples/01-google.php or https://github.com/reactphp/socket/blob/master/examples/11-http-client.php instead.

**Comment by wolrd** [comment]
@clue I want to send the text to the server:
`$conn->write('worker start');`

And I want the server to send this message back:
```
foreach ($socket->getConnections() as $connection) {
   $connection->write($data);
 }
```

How can I do it? 
I did this way:
```
$this->loop = \React\EventLoop\Factory::create();
        
        // Create server socket.
        $connector = new \React\Socket\Connector($this->loop);
        $connector
            ->connect('5.45.112.51:8081')
            ->then(
                function (\React\Socket\ConnectionInterface $conn)  {
                    $conn->write('worker start');
                    $conn->on('data', function($data){
                        $this->loop->stop();
                    });
                }
            );
        $this->loop->run();

```
Is it right?

**Comment by clue** [comment]
@wolrd Sounds about right. Are you having any issues with this code?

The above snippet will send some data to all your connections.

The below snippet will connect to your server once, send some data and then close the connection (without waiting for any incoming data).

**Comment by wolrd** [comment]
@clue Thank you! It works.

**Comment by wolrd** [comment]
I have one more question. How can I block the port (8081) from external requests?
`$socket = new \React\Socket\Server('127.0.0.1:8081', $loop);`

**Comment by clue** [comment]
@wolrd Looks good to me. Are you having any issues with this code?

If you use `127.0.0.1:x` as a listening address, this socket will bind to your loopback/localhost interface only and as such nobody from outside your system will be able to connect to this server instance.

**Comment by wolrd** [comment]
@clue thanks! It works:
This '127.0.0.1' is right. 'xxx.xx.xxx.xx' is wrong.
