### ISSUE TITLE
How to reconnect a client automatically?

### ISSUE THREAD

**Issue by wolrd** [reactphp/socket#155]
I want to reconnect to the server.
I found an [example ](https://stackoverflow.com/questions/43178554/how-to-reconnect-a-client-automatically-on-ratchetphp/43179353#43179353)on ratchetphp. 

It doesn't work for ReactPHP:
```
$connector = new \React\Socket\Connector($this->loop);
        $connector
            ->connect(sprintf('%s:%s', $host, $port))
            ->then(
                function (\React\Socket\ConnectionInterface $conn)
                {
                    $conn->on('close', function()
                    {
                        echo "close\n";
                        $this->loop->addTimer(10.0, function () {
                            
                            // RECONNECT HERE
                            $this->connector
                               ->connect('127.0.0.1:8061')
                               ->then( function (\Exception $e)
                               {
                               });

                        });
                    });
                }
       );
```
How to reconnect a client automatically?

**Comment by clue** [comment]
@wolrd The gist of this looks about this: `on(close) => connect()`

Are you having any issues with this code? It's unclear what problem you're seeing and where the variables come from and what events are actually fired in your particular setup.

That being said, it looks like your question might be out of scope for this project. If you're new to the concept of sockets, I would suggest redirecting this question at Stackoverflow.

I hope this helps :+1:

**Comment by wolrd** [comment]
@clue thanks. This is the [answer](https://stackoverflow.com/questions/49705738/how-to-reconnect-a-client-automatically-on-reactphp).
