### ISSUE TITLE
server listening, client returns website

### ISSUE THREAD

**Issue by GluedToTheScreen** [reactphp/socket#156]
New to reactPHP and trying to set up on AWS EC2...

The PHP server side is listening... can telnet connect on the same server.  

When I try the PHP client side, however, it receives the default HTTPS web page for the domain AND is not "seen" in the console on the server side. I'm obviously missing something.

EDIT:  using a javascript client, I get this:
`WebSocket connection to 'wss://xxxxx.xxxxx.com/' failed: Error during WebSocket handshake: Unexpected response code: 200`

Seems the requests are not being filtered on the server side, though both start connections on port 8000.  I still need to do something on the server... but what?

pointers (please)?

**Comment by GluedToTheScreen** [comment]
another edit...

been able to connect with PHP client but is horribly slow (one minute waiting) with this...

<VirtualHost...

ProxyPass / https://127.0.0.1:8000/
ProxyPassReverse / https://127.0.0.1:8000/

Still not a solution but getting closer, it seems.

**Comment by clue** [comment]
Thank you for your reaching out, but unfortunately this question is somewhat beyond the scope of this project and I don't see how this could be answered without an in-depth understanding of your particular code.

As a first step, I would suggest making yourself familiar with the examples, the documentation and/or ReactPHP in general.

It *looks like* you may be looking for a WebSocket server? In this case, you may want to check out the excellent WebSocket server [Ratchet](http://socketo.me/) which builds on top of ReactPHP. For additional help, you may want to check out the common community channels (such as IRC, StackOverflow etc.).

I hope this helps and you understand I'm closing this ticket for now. If your problem persists and you feel this is an issue that targets a broader audience, please comment back and we can re-open this. :+1:
