### ISSUE TITLE
send each message individually 

### ISSUE THREAD

**Issue by mahmood00** [reactphp/socket#157]
Im trying to use unix socket to send messages between php processes.

**Child process:**
```PHP 
$connector->connect('unix:///tmp/server.sock')
        ->then(function (ConnectionInterface $connection) use($loop) {
            $connection->write('from client to server 1');
            $connection->write('from client to server 2');
            sleep(10);
            $connection->write('from client to server 3');
        }, 'printf');

        $loop->run();
```

**Parent Process:**

```PHP
$loop = Factory::create();
$server = new Server('unix:///tmp/server.sock', $loop);

$server->on('connection', function (ConnectionInterface $client) use ($server) {
       $client->on('data', function ($data) use ($client, $server) {
                echo 'data: ' . $data . "\r\n";
        });
});

$server->on('error', 'printf');
$loop->run();
```

so after 10 seconds in the server side i got one message contains all the messages sent by the client process.

**How can i send each message individually?**
i want the flow to be like this: message 1 , message 2 , sleep 10 , message 3
not this: sleep 10  , (message 1 + message 2 + message 3)

**And What the maximum size for each message?** , since when i send big encoded array the server didn't receive anything?

**Comment by clue** [comment]
The `write()` method is guaranteed to be async (non-blocking). This implies that it is not guaranteed to write *immediately*.

ReactPHP works under the assumption that you use non-blocking functions,  Your `sleep()` call is blocking. As an alternative, consider using `$loop->addTimer()`. See also https://github.com/reactphp/react/wiki/FAQ#how-can-i-use-blocking-functions.

ReactPHP does not limit what kind of and how much data you transfer. You can use chunks of arbitrary sizes, however keep in mind it's usually a good idea to use piping if data is too big to fit into RAM.

I hope this helps :+1:
