### ISSUE TITLE
TCP_NODELAY socket option

### ISSUE THREAD

**Issue by librewind** [reactphp/socket#158]
Hello! I'm developing a networked multiplayer video game using websockets. I use this library (reactphp/socket) for websocket connection. But for real-time responses and low latency I need disable Nagle's algorithm. For disabling Nagle's algorithm typically use **TCP_NODELAY** socket option. Can you add using **TCP_NODELAY** socket option to library?

**Comment by andig** [comment]
I guess you should be able to use the connector's context option for that purpose?

**Comment by clue** [comment]
As of PHP 7.1.0 you can simply set the `tcp_nodelay` context option like this:

```php
$connector = new Connector($loop, array('tcp' => array('tcp_nodelay' => true)));
```

See https://github.com/php/php-src/commit/66fc5a343656509b8683d299f992836aab043bf7

I hope this helps :+1:

**Comment by librewind** [comment]
I need 'tcp_nodelay' for Server, not Connector.

**Comment by clue** [comment]
You can assign the same context option for the server side:

```php
$server = new Server(8080, $loop, array('tcp' => array('tcp_nodelay' => true)));
```

I hope this helps :+1:

**Comment by librewind** [comment]
It's not work for server.

Example:
`
$ctxt = stream_context_create([
	"socket" => [
		"tcp_nodelay" => true
	]
]);

$clientStream = stream_socket_client(
	"tcp://www.php.net:80", $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $ctxt);

$clientSocket =
	socket_import_stream($clientStream);

var_dump(socket_get_option($clientSocket, SOL_TCP, TCP_NODELAY));


$serverStream = @stream_socket_server(
    "tcp://127.0.0.1:8888",
    $errno,
    $errstr,
    STREAM_SERVER_BIND | STREAM_SERVER_LISTEN,
    $ctxt
);
$serverSocket = socket_import_stream($serverStream);

//socket_set_option($serverSocket, SOL_SOCKET, TCP_NODELAY, 1);
var_dump(socket_get_option($serverSocket, SOL_SOCKET, TCP_NODELAY));
`

Output:
`
int(1)
int(0)
`

**Comment by kelunik** [comment]
@librewind Did you test whether the option is set on an accepted client?

**Comment by clue** [comment]
@librewind Have you looked at the link I've posted above? This is covered by PHP's test suite here: https://github.com/php/php-src/commit/66fc5a343656509b8683d299f992836aab043bf7#diff-28234e57e1c2aef2a27e74dd1bbc9824

**Comment by librewind** [comment]
I get it. Thank you, guys, for help! You are super! :+1: :+1: :+1:
