### ISSUE TITLE
header

### ISSUE THREAD

**Issue by wormen** [reactphp/socket#16]
tell me how to put in the library header?
`
header ('Access-Control-Allow-Origin: *');
`
It does not work

**Comment by cboden** [comment]
This is the socket server library. It asynchronously serve raw data over streams. You're trying to set an HTTP header. See [reactphp/http](https://github.com/reactphp/http)

**Comment by wormen** [comment]
made as in the example, the result is still not fulfilled the title

```
$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);

$http = new React\Http\Server($socket);
$http->on('request', function ($request, $response) {
    $response->writeHead([200, 'Access-Control-Allow-Origin' => '*']);
    $response->end("");
});
$socket->on('connection', function ($conn) {
    $conn->on('news', function ($data) use ($conn) {
        $conn->write("ok");
    });
});
$socket->listen(1337, 'localhost');
$loop->run();
```
