### ISSUE TITLE
How can connect with socket.io?

### ISSUE THREAD

**Issue by engelsizmuzik** [reactphp/socket#163]
How do I connect to the socket socket of my socket with react.php?
How do I exchange data with socket.io?

I'm sorry for my bad english

**Comment by clue** [comment]
Socket.io uses a WebSocket transport, so you may want to use https://github.com/ratchetphp/Pawl as a WebSocket client to connect to any WebSocket server. To the best of my knowledge, there's no Socket.io implementation for ReactPHP, but maybe you can build one on top of Pawl? :shipit: 

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
