### ISSUE TITLE
One more write buffer thread.

### ISSUE THREAD

**Issue by mastir** [reactphp/socket#165]
code from guide (https://reactphp.org/socket/#quickstart-example)

```
$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop);

$connector->connect('127.0.0.1:8080')->then(function (ConnectionInterface $conn) use ($loop) {
    $conn->pipe(new React\Stream\WritableResourceStream(STDOUT, $loop));
    $conn->write("Hello World!\n");
});

$loop->run();
```
Simple do not ever send "Hello World".

 I need to send 12-18 bytes every 30 seconds. And server to answer "ok" with 4 bytes. 
**Is there any simple way to trigger buffer flush without endless silence?**

Client will send same package 3 times and disconnect if there is no "ok" reply, wait 30 seconds and endless silence game start over and over again.

**Comment by clue** [comment]
HI @mastir, that's an interesting find! This `write()` call should happen pretty much instantly, so that your local server should receive this no later than in a millisecond or two.

I wonder if this issue could be the `WritableResourceStream` and the lack of error handling in this example. Are you running this on Windows? Windows is known to reject process pipes such as `STDOUT` as documented here: https://github.com/reactphp/stream#writableresourcestream

You can try moving the stream instantiation outside of the connection handler like this:

```php
$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop);
$out = new React\Stream\WritableResourceStream(STDOUT, $loop);

$connector->connect('127.0.0.1:8080')->then(function (ConnectionInterface $conn) use ($out) {
    $conn->pipe($out);
    $conn->write("Hello World!\n");
});

$loop->run();
```

**Comment by mastir** [comment]
Hi @clue i'll try to reproduce it in simple way.
i removed all the application logic, now server code is simple:
```
$loop = React\EventLoop\Factory::create();
$server = new React\Socket\Server('0.0.0.0:16016', $loop);
$server->on('connection', function($connection){
	$ip = trim(parse_url($connection->getRemoteAddress(), PHP_URL_HOST), '[]');
	echo '[conn] '.$ip.' connected'.PHP_EOL;
	$buffer = '';
	$connection->on('data', function ($chunk) use ($ip, $connection, $buffer) {
		echo '[data] '.$ip.' '.$chunk.PHP_EOL;
	});
	$connection->on('error', function (Exception $e) use ($ip) {
	    echo  '[conn] '.$ip.' error: ' . $e->getMessage().PHP_EOL;
	});
	$connection->on('close', function () use ($ip) {
	   echo '[conn] '.$ip.' closed.'.PHP_EOL;
	});
});
$loop->run();
```
and client:
```
$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop);

$connector->connect('127.0.0.1:16016')->then(function ($conn) use ($loop) {
    $conn->pipe(new React\Stream\WritableResourceStream(STDOUT, $loop));
    $conn->write("Hello World!\n");
});

$loop->run();
```
terminal
```
$ uname -a
Linux host 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:25 UTC 2017 i686 i686 i686 GNU/Linux
user@host:~/$ php7.1 EchoServer.php
[conn] 127.0.0.1 connected
[conn] 127.0.0.1 closed.
[conn] 127.0.0.1 connected
[conn] 127.0.0.1 closed.
[conn] 127.0.0.1 connected
^C
```
and second terminal
```
user@host:~/$ php7.1 HelloClient.php
^C
user@host:~/$ php7.1 HelloClient.php
^C
user@host:~/$ php7.1 HelloClient.php
```

And after i changed port number the problem is gone. 
**Thanks a lot!**
