### ISSUE TITLE
Does this component support client certificates?

### ISSUE THREAD

**Issue by korotovsky** [reactphp/socket#172]
Hi,

I could not find in the docs, looks like it comes from ssl context but I'm still not sure...

In my case I have self-signed HTTPS and CA for client certificates.

What kind of options I have to provide in this case?

Thanks

**Comment by clue** [comment]
Hi @korotovsky! Yes, this project supports all TLS (formerly known as SSL) context options that are supported by PHP (http://php.net/manual/en/context.ssl.php), as they are simply passed through to the underlying PHP functions.

To request client certificates on the server side this means that you will need to set the `capath` and `verify_peer=true`.

To send client certificates on the client side this means that you will need to set the `local_cert` (and possibly `passphrase`).

I hope this helps :+1:
