### ISSUE TITLE
Can I make a tcp server and it can handle http request and raw tcp.

### ISSUE THREAD

**Issue by losywee** [reactphp/socket#174]
Can I make a tcp server and it can handle http request and raw tcp.

**Comment by clue** [comment]
@losywee Excellent question.

HTTP uses the TCP/IP transport, so you can listen on your TCP/IP socket to check which protocol the client is using. This is sometimes called "protocol multiplexing" or "port sharing" and its implementation may or may not be a little more involved than your average protocol listener.

If you're looking for existing projects using this, perhaps take a look at sslh and others.

If you're looking for existing projects using this with this component, perhaps take a look at https://github.com/leproxy/leproxy/blob/master/src/ProtocolDetector.php which uses HTTP and SOCKS over the same port.

As a rule of thumb: You should probably use different port for each protocol, unless you have some good reasons to share ports.

I hope this helps :+1:
