### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Valantir007** [reactphp/socket#175]
Hi, I have big problem with my script and want to figure out what I am doing wrong or this is the problem with those library.

I have server:

```
$loop = new React\EventLoop\Factory::create();
$unixServer = new UnixServer('rabbit_socket.sock', $loop);
$server = new LimitingServer($unixServer, 1);
$server->on('connection', function (ConnectionInterface $connection) {
    $connection->on('data', function ($data) use ($connection) {
        $connection->write('test');
        $connection->end();
    });

});
$loop->run();
```

And now I check memory usage (columns: VSZ and RSS) via ps aux:

![image](https://user-images.githubusercontent.com/3719513/45878612-04579380-bda2-11e8-8cce-99a8a1089527.png)

![image](https://user-images.githubusercontent.com/3719513/45878628-15a0a000-bda2-11e8-9ffb-290b96c73e75.png)

![image](https://user-images.githubusercontent.com/3719513/45878670-3963e600-bda2-11e8-8742-7a9c04f7a4b7.png)

How you can see - memory usage increase. What I'am do wrong? I want to run server and send from client just one message and than disconnect client.

**Comment by clue** [comment]
@Valantir007 Thanks for reporting!

We're not aware of any memory leaks in this project or any of the related ReactPHP projects.

Your example appears to monitor memory usage for 3(?) connections only. PHP performs a number of (internal) memory allocations that are outside our control. It may keep references alive even after we no longer reference them in our code for a limited period. Monitoring this for a longer period of time (and possibly thousands of connections) should show that memory usage does not show any significant spikes. You may see memory usage increase slightly and then decrease again. This should never climb to unreasonable values, but other than that it's really out of our control.

I hope this helps :+1:

**Comment by Valantir007** [comment]
@clue Thanks for reply :)

No, I have many connections from api and after long time, I see the problems with memory usage. I wonder what can be the reason, because after 100 - 150 connections I was noticing, that memory increased. How do you think - can be the php7 internaly problem or server configuration? I'm losing ideas.

**Comment by clue** [comment]
This shouldn't happen... Can you show us a gist of the code you're having memory issues with and the steps to reproduce this locally?

**Comment by Valantir007** [comment]
Ok, I found it. The problem is one extension for php. Not react/socket package. I apologize for suspicion ;)

**Comment by clue** [comment]
@Valantir007 Thank you for reporting back and happy to hear that both your problem is resolved and that this is not an issue in this project :-)

**Comment by Meinder-A** [comment]
> Ok, I found it. The problem is one extension for php. Not react/socket package. I apologize for suspicion ;)

hello, i'm also facing some memory leak cases... Do you remember what was the extension?

Thanks :)
