### ISSUE TITLE
Connection succeeds despite invalid bind address

### ISSUE THREAD

**Issue by Tatikoma** [reactphp/socket#195]
Hello. I creating socket with bindto tcp context option, to connect from specified network interface. Sometimes network interface may be not available (usb modem sometimes hangs and reboots), but connection was created, what it doesnt acceptable for me because routing for this connection 'll be wrong.

Sample code:
```php
$connector = new React\Socket\Connector($loop, array(
    'tcp' => array(
        'bindto' => '1.2.3.4:0'
    ),
));

$connector->connect('8.8.8.8:53')->then(function (React\Socket\ConnectionInterface $connection) {
    // ...
});
```

stream_socket_client method generates PHP Warning when creating socket with nonexistent bindto interface option. errstr and errno remains empty.

So i need to change behavior, if socket created with errors i wanna to close socket immediately and reject attempt. To keep backward compatability i suggest adding option like "is_allow_socket_with_errors" to Connector (or to TcpConnector?) class. To check if error exists i can use set_error_handler and restore_error_handler methods.

If my approach is ok, then i can write code and send pull request. syn/ack/rst 'll be produced in this case, so i checking if interface is available before creating connection using shell_exec and ifconfig, but sometimes it doesnt help.

**Comment by clue** [comment]
@Tatikoma Thanks for reporting, this sure sounds like an *interesting* problem you're facing :-)

I've tried this out locally and can indeed reproduce the problem you're seeing with plain PHP like this:

```php
$context = stream_context_create(array('socket'=>array('bindto'=>'1.2.3.4:5678')));

$stream = stream_socket_client('tcp://google.com:80', $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $context);
> PHP Warning:  stream_socket_client(): failed to bind to '1.2.3.4:5678', system said: Cannot assign requested address in {file} on line {line}

var_dump($stream);
> resource(415) of type (stream)

var_dump(stream_socket_get_name($stream, false));
> string(19) "192.168.43.75:46144"
```

> stream_socket_client method generates PHP Warning when creating socket with nonexistent bindto interface option. errstr and errno remains empty.

Indeed. The script above shows how this does report PHP Warning message but still continues to connect to the destination server nonetheless. Likewise, if it can not reach the destination at all, it will report two PHP Warnings and only then fail the attempt. Afaict it looks PHP might be at fault here for trying to continue connecting if the underlying `bind()` call fails. Perhaps this is something we may want to push upstream instead and perhaps figure out the motivation for this decision?

> So i need to change behavior, if socket created with errors i wanna to close socket immediately and reject attempt. To keep backward compatability i suggest adding option like "is_allow_socket_with_errors" to Connector (or to TcpConnector?) class. To check if error exists i can use set_error_handler and restore_error_handler methods.

We currently suppress any PHP Warnings as part of the `TcpConnector` and only fail the connection attempt if the `stream_socket_client()` call returns an error. Currently, this means that you should not see any error message if the `bind()` call fails, but the connection succeeds.

You might be able to just check the local address of the connection through `getLocalAddress()` to see if your `bind()` call was rejected and manually handles this situation in your application (closing the connection and/or logging an error). TBH I'm not a big fan of adding a flag ("boolean trap") to configure this behavior as part of this library. If we want to address this in this library, it's my understanding the connection should never succeed in the first place.

What do you think, does this help with the problem you're seeing?

**Comment by clue** [comment]
For the reference, the behavior seems to occur on all PHP versions as of PHP 5.1 (which is where the `bindto`) option was first added: https://3v4l.org/GkN7F and http://php.net/manual/en/context.socket.php#refsect1-context.socket-changelog

PHP's source code suggests this only applies to client side connections, but not to the server side: https://github.com/php/php-src/blob/623911f993f39ebbe75abe2771fc89faf6b15b9b/main/network.c#L876 and https://github.com/php/php-src/blob/623911f993f39ebbe75abe2771fc89faf6b15b9b/main/streams/transports.c#L157

**Comment by Tatikoma** [comment]
Thanks for your response.
You are totally right, getLocalAddress 'll solve my issue (a bit).

**Comment by clue** [comment]
> I was sent bug report to PHP, maybe this behavior 'll be changed in the future.
https://bugs.php.net/bug.php?id=77661

Thank you very much for reporting this upstream! :+1: 

> […] Looks like i need to create proxy class for TcpConnector to override connect method. Right?

Sounds about right :+1: This "proxy class" should decorate an existing connector and can then be used in any place where you would normally use a connector, so this shouldn't be limited to SOCKS or any other protocol.

I believe this has been answered and don't think there's much that needs to be done here, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
