### ISSUE TITLE
how to run server in daemon mode?

### ISSUE THREAD

**Issue by sidealice** [reactphp/socket#203]
how to run tcp/http server in daemon(backend) with socket module?

thanks

**Comment by clue** [comment]
@sidealice Welcome to @ReactPHP :tada: 

Unlike traditional PHP code, this project is usually used in a long running process. How you keep this process running in the background is left up to your environment, but most people use systemd, supervisord or docker to run and monitor this process, see also https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6 as a starting point.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by kailasb10** [comment]
I've set the server to run continuously using supervisor but I've to restart the supervisor manually every day at midnight to work properly for the day.

How can we avoid this?

**Comment by WyriHaximus** [comment]
@kailasb10 Is this the same issue as you opened #259 for?

**Comment by kailasb10** [comment]
yes. I've found the issue. you can see the solution at [https://github.com/reactphp/socket/issues/259](url)
