### ISSUE TITLE
send one message but receive 2 chunks

### ISSUE THREAD

**Issue by VoldemarOzzy** [reactphp/socket#204]
Hi, could someone please help as I am stuck.  I am starting server 
```php
$SocketServer = new React\Socket\Server("host:port", $loop);
$SocketServer->on('connection', function (ConnectionInterface $connection)  {
        $connection->on('data', function ($data){
echo "\$data=$data";
        });
    });
```
When I send {"PING":"1561715200.438945055"}

I have two lines :
Line 1: 
$data={
Line 2: 
$data="PING":"1561715200.438945055"}

Unfortunately at this stage it is difficult to understand if line 1 was from previous command or not.
Why  I have 2 lines? Am i misunderstoond a concept or something? If anybody could clarify that would be great! Thank you.

**Comment by WyriHaximus** [comment]
Hey so simply put this is how it works. We get the data in chunks from the kernel and don't know the supposed format. So we pass it on as is. My guess is that you're using JSON with new lines between them so this package might be interesting: https://github.com/clue/reactphp-ndjson

**Comment by clue** [comment]
@VoldemarOzzy What @WyriHaximus said :-)

What you're looking for is called "message framing" which isn't provided by TCP/IP on its own. You can use some delimiters between messages (like NDJSON) or use length indicators like netstrings, see also https://github.com/reactphp/socket/issues/166 for possible duplicate.

**Comment by VoldemarOzzy** [comment]
Thank you WyriHaximus!
Thank you clue!
for pointing me in right direction! I have just fixed the this. Appreciate!
