### ISSUE TITLE
How to connect to websocket and send a header to Sec-WebSocket-Protocol:admin?

### ISSUE THREAD

**Issue by StringKe** [reactphp/socket#205]
I need to connect a websocket but it needs a header as a security check
`Sec-WebSocket-Protocol:admin`

```php
$loop = Factory::create();
        $connector = new Connector($loop);
        $connector->connect('ws://118.24.159.166:23333')->then(function (ConnectionInterface $connection) use ($loop) {
            $connection->on('data', function ($data) {
                $this->warn($data);
            });
            
            $connection->write("Sec-WebSocket-Protocol: admin\r\n");
        });
        $loop->run();
```

**Comment by clue** [comment]
Hi @StringKe, welcome to @ReactPHP! :tada: 

It looks like you're running a plaintext TCP/IP socket client and are trying to use the WebSocket protocol to communicate with this server? You can use this project as a low-level library to send the required TCP/IP data, but it's unlikely you want to re-implement this protocol from scratch.

It *looks like* you may be looking for a WebSocket client, such as the one provided by your browser to connect to a WebSocket server? In this case, you may want to check out the excellent WebSocket client [Pawl](https://github.com/ratchetphp/Pawl) which builds on top of this project.

I hope this helps :+1:

**Comment by StringKe** [comment]
> Hi @StringKe, welcome to @reactphp! 
> 
> It looks like you're running a plaintext TCP/IP socket client and are trying to use the WebSocket protocol to communicate with this server? You can use this project as a low-level library to send the required TCP/IP data, but it's unlikely you want to re-implement this protocol from scratch.
> 
> It _looks like_ you may be looking for a WebSocket client, such as the one provided by your browser to connect to a WebSocket server? In this case, you may want to check out the excellent WebSocket client [Pawl](https://github.com/ratchetphp/Pawl) which builds on top of this project.
> 
> I hope this helps

Thank
