### ISSUE TITLE
Ignoring exceptions from HappyEyeBallsConnectionBuilder::resolve

### ISSUE THREAD

**Issue by Provoker** [reactphp/socket#248]
HappyEyeBallsConnectionBuilder::connect ignores rejection HappyEyeBallsConnectionBuilder::resolve if there is no A or AAAA dns entry.

This fact has no effect in the current implementation of promise, but if you add a detector of unhandled rejections, it will cause problems.
And based on your plans, this detector will still be added (https://github.com/reactphp/promise/pull/170) and the problem will still have to be corrected.

We are already using our own implementation of handling uncaught rejections at the moment and this problem prevents us from upgrading to a version higher than 1.3.0.

**Comment by WyriHaximus** [comment]
Hey @Provoker thank you for reporting this bug. But "issue" might have slipped by us when implementing Happy Eyeballs. You can still update to 1.6, and disable happy eyeballs as documented at https://reactphp.org/socket/#connector with the following snippet: 

```php
$connector = new React\Socket\Connector($loop, array(
    'happy_eyeballs' => false
));
```

 I'll have a look at this this week and come up with a fix :+1:

**Comment by WyriHaximus** [comment]
@Provoker just filed #251 to fix this
