### ISSUE TITLE
[Server] Add support for Unix domain sockets (UDS)

### ISSUE THREAD

**Issue by clue** [reactphp/socket#25]

**Comment by clue** [comment]
See PR #17 for possible implementation.

**Comment by clue** [comment]
Progress update: Feature branch is ready, I'll file a PR for this once the v0.5.0 release is out :shipit:

**Comment by WyriHaximus** [comment]
🎉

**Comment by clue** [comment]
Deferred to future release as per #75

**Comment by andig** [comment]
Checking back here. It seems UDS Connector has meanwhile been merged, but UDS Server still seems missing. It might also make sense to enhance `Server` to create the underlying UDS/TCP/Secure server according to URI instead of proxying a `TcpServer`?

**Comment by clue** [comment]
@andig Correct :+1: We're currently focusing our efforts on the HTTP component and on stabilizing things, but in the meantime I suppose we would be super happy to accept new feature PRs :+1:

**Comment by clue** [comment]
This feature was originally planned for the v1.1.0 release milestone, but given the awesome PR #25 by @andig, it's safe to get this in with the next v0.8.6 release already :shipit: :tada:
