### ISSUE TITLE
Additional suggestion

### ISSUE THREAD

**Issue by xxAROX** [reactphp/socket#253]
Maybe make something like [this](https://github.com/aeberdinelli/express-php).

**Comment by clue** [comment]
@xxAROX Welcome to @ReactPHP 👋

This component provides low-level sockets for any ReactPHP-based application. HTTP applications should use https://github.com/reactphp/http which builds on top of the lower-level sockets.

There are also a number of web applications (or frameworks) that build on top of this HTTP component. You're welcome to contribute to this ecosystem if you feel an express-like framework is needed (I love the idea)! Cheers! 👍

**Comment by xxAROX** [comment]
okay

**Comment by xxAROX** [comment]
but idk how pull requests work..
and my php experience is not the best :)
