### ISSUE TITLE
Listening multiple socket chanels on the same server

### ISSUE THREAD

**Issue by bobimicroweber** [reactphp/socket#272]
Hello, how can i make a multiple socket channel listen the same server.
So i want to subscribe to binance socket to listen the many binance accounts and receive their user data actions.
I try to make a socket listening in foreach but , only one listenin is activated.. another ones its not.
Can  you guys help me

**Comment by clue** [comment]
There are no known limitations, so creating any number of connections works just fine. If you're seeing any issues, please share more details such as error messages and a gist to reproduce and we're happy to take a look at this.

In the meantime, I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
