### ISSUE TITLE
[v1.11.0] Accessing array offset on null value - Failed TCP connection without ext-sockets

### ISSUE THREAD

**Issue by matheusb-comp** [reactphp/socket#286]
I'm receiving the following error in [this line](https://github.com/reactphp/socket/blob/master/src/TcpConnector.php#L123):
```
   ErrorException  : Trying to access array offset on value of type null

  at /var/www/html/vendor/react/socket/src/TcpConnector.php:123
    119|                         @\fwrite($stream, \PHP_EOL);
    120|                         $error = \error_get_last();
    121| 
    122|                         // fwrite(): send of 2 bytes failed with errno=111 Connection refused
  > 123|                         \preg_match('/errno=(\d+) (.+)/', $error['message'], $m);
    124|                         $errno = isset($m[1]) ? (int) $m[1] : 0;
    125|                         $errstr = isset($m[2]) ? $m[2] : $error['message'];
    126|                     } else {
    127|                         // Not on Linux and ext-sockets not available? Too bad.

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Trying to access array offset on value of type null", "/var/www/html/vendor/react/socket/src/TcpConnector.php")
      /var/www/html/vendor/react/socket/src/TcpConnector.php:123

  2   React\Socket\TcpConnector::React\Socket\{closure}()
      /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php:253

  Please use the argument -v to see more details.

```

The `$error` is `null`, but I have no idea why.
I'm using [another library](https://github.com/beyondcode/laravel-websockets) that depends on this one indirectly.

The composer require tree:
```
beyondcode/laravel-websockets 1.8.1 An easy to use WebSocket server
├──cboden/ratchet ^0.4.1
│  └──react/socket ^1.0 || ^0.8 || ^0.7 || ^0.6 || ^0.5
└──clue/buzz-react ^2.5
   ├──react/http-client ^0.5.10
   |  └──react/socket ^1.0 || ^0.8.4
   └──react/socket ^1.1
```

PHP version:
```
PHP 7.4.27 (cli) (built: Dec 16 2021 22:42:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by clue** [comment]
@matheusb-comp Thank you for reporting, I can indeed reproduce the problem you're seeing provided *all* of the following prerequisites are met:

* Creating a connection that fails (e.g. connection refused) and
* `ext-sockets` is not available (installed by default on most platforms) and
* Running on Linux (#266 specifically targets Linux only) and
* Using a global error handler (`set_error_handler()`)

I've started looking into this and will file a PR as soon as time permits coming up with some reproducible test cases. Expect an update no later than a week or two.

In the meantime, it should be easy enough to work around this by making sure any of the items from the above list are no longer true, e.g. by installing `ext-sockets`.

**Comment by matheusb-comp** [comment]
> * `ext-sockets` is not available (installed by default on most platforms)

The code is running inside a Docker container that does not have the `sockets` module by default.
Thanks for the help, after installing the module it no longer fails.

<details>
  <summary>Default PHP modules on php:7-fpm-alpine</summary>
  <pre>
$ docker run --rm -it --entrypoint sh php:7-fpm-alpine
/var/www/html # php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]
  </pre>
</details>
