### ISSUE TITLE
How to handle socket connection on  Server 

### ISSUE THREAD

**Issue by ChintanStratAero** [reactphp/socket#287]
I am building Socket TCP Server for laravel .
 I want to keep all the connections alive till i don't do connection->close(). But when i do connectionWrite->write ("Hello world") the message is depicted on client screen but connection is also closed. I don't want the connection to die. I want to reuse the connection in future transaction with server. I don't want to close the connection as it does on its own. I am using Postman like Nightingale for testing( as a client).
![Question on socket](https://user-images.githubusercontent.com/22551270/158398855-b6b4fb32-d62a-496a-a305-09bbff736dd6.png)

**Comment by SimonFrings** [comment]
Hey @ChintanStratAero, thanks for bringing this up 👍

It looks like what you're seeing is normal HTTP behavior. After the client requests something and the server responds there's no need for the client to leave the connection open.  After receiving its answer the client may close the connection.

If you're using postman for testing purposes you're most likely speaking HTTP. You can take a look at https://github.com/reactphp/http, this may help!

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Comment by ChintanStratAero** [comment]
Yes sure thanks once again.

**Comment by ChintanStratAero** [comment]
Simon,
Thank you your response helped me. I created client in php which is
connected for ever and it working.
Thanks one more time..
