### ISSUE TITLE
How to deploy the server?

### ISSUE THREAD

**Issue by it19862** [reactphp/socket#293]
I want to test the server.
I'm using Windows-10.
I downloaded the files.
What do I need to install additionally on Windows-10 to test the server?
Where to place the project files?
Where to place and how to run the server file?
Where to place and how to run the client file?

**Comment by clue** [comment]
Hi @it19862 and welcome to ReactPHP! :-)

It's a bit unclear what you're trying to achieve exactly from the details you've posted and it sounds like you may be new to PHP. As a starting point, I would recommend checking out our website on https://reactphp.org/ and see if you can follow some of our quickstart examples.

If you have PHP installed and used Composer to install your package of choice, you should be able to run each example on the command line like `php examples/demo.php`. If you don't know where to start, you may also like to take a look at this: https://framework-x.org/docs/getting-started/quickstart/

I hope this helps! :+1:
