### ISSUE TITLE
Http streaming client

### ISSUE THREAD

**Issue by aali1** [reactphp/socket#36]
Is it possible to write a http streaming client using React?

I have an application which connects to a server and the connection remains open and data is passed through that stream

**Comment by clue** [comment]
> Is it possible to write a http streaming client using React?

Are you looking for https://github.com/reactphp/http-client? :)

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
