### ISSUE TITLE
No data returned from server written to socket before connection close

### ISSUE THREAD

**Issue by shilka** [reactphp/socket#37]
Hi!

I have a following code
```php
$socket->on('connection', function ($conn) 
{
  $conn->write("Hello there!\n");

  $conn->on('data', function ($data) use ($conn) {
    $conn->write("I have received a data!\n");
    $conn->close();
  });
});
```
The problem is I only receive "Hello there" string, but not "I have received a data!\n". I am not receiving second string even with sleep(5) or something before ```$conn->close()``` line. Is this a bug or I am doing something wrong?

Thank you in advance.

PS 

comoser: 
```
{
    "require": {
        "react/socket": "~0.4.0"
    }
}
```
php -v:
```
PHP 7.0.5 (cli) (built: Apr  2 2016 23:10:23) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by cboden** [comment]
`close` immediately closes the socket. Being an asynchronous environment that *could* happen before the `write` happens. Instead, use `$conn->end()`. That will close the connection after the write buffer has been drained.

**Comment by shilka** [comment]
```->end()``` works great, thank you!
