### ISSUE TITLE
No post data received

### ISSUE THREAD

**Issue by migmam** [reactphp/socket#39]
Hi,

I have a problem working with reactPHP (http server)

Scenario.

Apache receiving data
PHP script sending data via post to another server through a php script with curl to the reactphp server.
ReactPHP server sometimes receive data and sometimes not.

I have verified that from the apache server the data is always posted.

What is the problem then?

Thanks!

Please take a look at this simple code:

```
require 'vendor/autoload.php';

$loop   = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);
$http   = new React\Http\Server($socket, $loop);

$http->on('request', function ($req, $res) {

print_r($req);


    $req->on('data', function($data) use ($req, $res) {

            parse_str($data,$datos);
            if(count($datos)==0)
            {

                    echo "No data \n";
            }


            $res->writeHead(200,
            array(
                    'Access-Control-Allow-Origin'=>'*',
                     'Content-Type' => 'text/plain'
             ));

            $res->end("Ok\n");
    });

});

$socket->listen(5000,10.1.45.39);
$loop->run();
```

**Comment by clue** [comment]
Hi @migmam, it appears you're having an issue with react/http and not react/socket. May I ask you to file the problem in its repo instead? Thanks!

**Comment by migmam** [comment]
Hi @clue 

I have also tested with just react/socket and the result is the same.

Sometimes the posted data is not received.

This is my code.


```
<?php
require 'vendor/autoload.php';
$loop = React\EventLoop\Factory::create();

$socket = new React\Socket\Server($loop);
$socket->on('connection', function ($conn) {

$conn->write("Welcome to this amazing server!\n");
$conn->write("Here's a tip: don't say anything.\n");

    $conn->on('data', function ($data) use ($conn) {

        $request = explode("\n",$data);
        $request_properties = explode(" ",$request[0]);
        $method = $request_properties[0];
        $routes = explode("/",substr($request_properties[1],1));

        parse_str($request[5],$posted_data);
        print_r($posted_data);
        $conn->close();
    });
});
$socket->listen(5000,'10.1.45.36');
$loop->run();
?>
```

So the $posted_data is empty.

**Comment by clue** [comment]
Thanks for posting back with more details :+1: 

> I have also tested with just react/socket and the result is the same.

So what exactly is the issue here? :)

Your example code starts processing once the first "data" event is emitted. Note that this event will be emitted once first chunk has been received, i.e. it does not necessarily include *everything* the sender intended to send at once. Depending on what you're doing here, you would usually use a framing protocol on top of the underlying streaming protocol so you can know how much of your data makes up a single "message".

It still looks like you're using HTTP (or HTTP-like protocol) here, so perhaps react/http would still help?

**Comment by migmam** [comment]
Hi @clue. Thanks for your answer. 
I'm going to test it again and again because when the data is send from one server to itself ..it fails (no post data is received every since in a while)..but when I send data from one server (apache) to other server (react) it works correctly. It is a very strange behaviour. I will keep you updated.

**Comment by LeonanCarvalho** [comment]
I got same here:

Code:
```php
<?php
include_once './vendor/autoload.php';

$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);
$http = new React\Http\Server($socket);
$http->on('request', function ($request, $response) {
    $headers = array('Content-Type' => 'text/plain');
    $sink = new React\Stream\BufferedSink();
    $request->pipe($sink);

    $sink->promise()->then(function ($requestBody) use ($response, $headers) {
        parse_str($requestBody, $requestData);
        var_dump($requestBody, $requestData);

        $response->writeHead(200, $headers);
        $response->end("Hi, thanks man.\n");
    });
    $request->close();
});

$socket->listen(5050);
$loop->run();
```

Request:

```cmd
curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d 'd=22&f=f&f=f&f=f' "http://localhost:5050/notify"
```
Received:

```
 //$requestBody : 
string(0) ""
// $requestData :
array(0) { 
}
``

**Comment by clue** [comment]
Ping @migmam, can you update the status here, does the problem persist or did you mange to resolve this in the meantime?

**Comment by migmam** [comment]
Hi Christian

It is not related to reactphp/socket. The tests I performed shown that it
was related (if so) with reactphp/http but not clearly sure.
I changed my code that was calling to reactphp/http from file_get_contents
to curl and the results were ok.

Regards,

Miguel Angel


2016-11-13 13:48 GMT+01:00 Christian Lück <notifications@github.com>:

**Comment by clue** [comment]
Thanks for reporting back! :+1: I'll assume this is resolved and will close this for now, please feel free to report back otherwise.
