### ISSUE TITLE
Extend ConnectionInterface with ports / target address.

### ISSUE THREAD

**Issue by SamMousa** [reactphp/socket#41]
(Related to #26)

I'm implementing the proxy protocol for react:
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

Even though not all transports have a separate port part, I think it would be nice to add some more methods to the connection interface:
````
public function getTargetAddress();
public function getTargetPort();
public function getRemotePort();
````

-- Part below is about the naming of entities in the connection interface --

Also naming could possibly be reconsidered. Connections always have a direction (source and target), but the concept of local and remote does not always apply. I understand that `getRemoteAddress()` refers to the "other" end of the connection, but it could be more consistent when we use source and target.
When looking at it from a more abstract viewpoint:

Consider: 
Client `A` connects to Server `B` to establish a Connection `C`
Both `A` and `B` both have an object representing C, say C_a and `C_b`
Using terms like `remoteAddress` and `localAddress` creates the following relation:
````
C_a.remoteAddress = C_b.localAddress 
and 
C_a.localAddress = C_b.remoteAddress
````
When multiple connections are managed, both inbound and outbound, we need to "know" where the connection came from to decide which party we are (local or remote).

**Comment by SamMousa** [comment]
@clue As far as I can tell all Layer 4 protocols have a source and target port. How about adding a `OsiLayer4ConnectionInterface` for those? That would be a relatively simple extension and OSI layers are pretty well defined.

**Comment by clue** [comment]
```
C_a.remoteAddress = C_b.localAddress 
and 
C_a.localAddress = C_b.remoteAddress
```

I think this makes sense :+1:  Though I'm not sure what you're suggesting we need to do? :)

> When multiple connections are managed, both inbound and outbound, we need to "know" where the connection came from to decide which party we are (local or remote). 

I'm not sure I follow, can you elaborate on this? You usually hold a reference to an instance representing the connection, so how exactly can these be mixed up?

> How about adding a `OsiLayer4ConnectionInterface` […]

Care to elaborate on this? What's the motivation for this interface? What does this interface do that the `ConnectionInterface` is not capable of?

**Comment by SamMousa** [comment]
I'd like to have a `getSourceAddress` and `getTargetAddress` although when thinking about it more, for unix sockets it could be argued that there is no real source address...

> I'm not sure I follow, can you elaborate on this? You usually hold a reference to an instance representing the connection, so how exactly can these be mixed up?
I guess it depends on if you use the connection instance passed in the callback or the one you stored upon connection initiation.

> Care to elaborate on this? What's the motivation for this interface? What does this interface do that the ConnectionInterface is not capable of?
It could expose things like the port which are part of the OSI 4 layer (afaik).

**Comment by clue** [comment]
> > I'm not sure I follow, can you elaborate on this? You usually hold a reference to an instance representing the connection, so how exactly can these be mixed up?
> 
> I guess it depends on if you use the connection instance passed in the callback or the one you stored upon connection initiation.

I'm still not sure I follow. Incoming and outgoing connections use different classes, as they're from different components. Using `instanceof` is much more reliable than checking the addresses (e.g. think of connections to localhost).

> It could expose things like the port which are part of the OSI 4 layer (afaik).

You've got me confused, are we talking about #26 here? :-) If so, let's please move the discussion into a single ticket.

**Comment by SamMousa** [comment]
Ok.
