### ISSUE TITLE
Server::createConnection breaks SRP

### ISSUE THREAD

**Issue by SamMousa** [reactphp/socket#44]
Shouldn't a `ConnectionFactory` be passed into `Server::__construct` instead of having a hardcoded classname in `createConnection`?
According to the single responsibility principle usage of an object should be separate from its construction right?

**Comment by clue** [comment]
I think this makes sense :+1: Out of curiosity, do you have any practical use case for this?

**Comment by SamMousa** [comment]
@clue Yes I do, since it is hard to get traction for changing the `ConnectionInterface` (since not all connections have a port), it makes sense to have different connection interfaces and different underlying implementations. This would allow you to use such a different connection implementation without changing the server.

**Comment by clue** [comment]
Ping @SamMousa, what do you think, is this and #47 still relevant now that #65 is in? :+1:

**Comment by clue** [comment]
I believe this has been addressed via #65. Closing this due to a lack of feedback. If you feel this problem persists, please comment on this and we can reopen this :+1:
