### ISSUE TITLE
$loop visibility prevent from extending Server

### ISSUE THREAD

**Issue by jason69** [reactphp/socket#53]
Hi,
in ```Server``` class
```loop``` property is defined as ```private```

Is there a specific reason for this?
Could it be ```protected```?
Class can't be extended because of that...
Reason why one would extend: add context options or flags to ```stream_socket_server```

**Comment by clue** [comment]
>The `$loop` is private because we don't want this to become part of our public API. Keeping this private allows us to change these implementation details without introducing BC breaks.

>I agree that keeping this as-is encourages a cleaner design because it makes `extend`ing the server more difficult and encourages composition (DI) instead.

>This has also already been covered in #12, #14 and #27.

> I hope this helps :+1: I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we may reopen this :+1:

https://github.com/reactphp/socket/issues/40#issuecomment-260184548
