### ISSUE TITLE
Cannot bind IPv6 [::] (any)

### ISSUE THREAD

**Issue by maxxer** [reactphp/socket#58]
```php
        $loop = \React\EventLoop\Factory::create();
        $ip4 = new \React\Socket\Server($loop);
        $ip6 = new \React\Socket\Server($loop);
        $ip4->listen(9988, '0.0.0.0');
        $ip6->listen(9988, '::');

        $wsStack = new \Ratchet\Http\HttpServer(
            new WsServer(
                new Online()
            )
        );

        $ip4App = new IoServer($wsStack, $ip4, $loop);
        $ip6App = new IoServer($wsStack, $ip6, $loop);
        $loop->run();
```

This fails with:
`Exception 'React\Socket\ConnectionException' with message 'Could not bind to tcp://[::]:9988: Address already in use'`

But address is not in use, in fact if I replace *::* with the actual machine public IPv6 address works fine.

**Comment by clue** [comment]
Thanks for reporting!

The example code essentially executes this under the hood:

```php
$a = stream_socket_server('tcp://0.0.0.0:9988');
$b = stream_socket_server('tcp://[::]:9988');
```

Which emits the very same error.

If you omit the first server, then the second works just fine. It looks like this is intended behavior.

I hope this helps :+1:

**Comment by maxxer** [comment]
If that's intended how to open a socket for both v6/v4?

**Comment by maxxer** [comment]
Maybe this is related? 
https://bugs.php.net/bug.php?id=73307

**Comment by maxxer** [comment]
I'm on linux and indeed this happens to be true. Using just the IPv6 *[::]* address listens on both the stacks, because my ubuntu server has 0 in `/proc/sys/net/ipv6/bindv6only`

**Comment by clue** [comment]
Thanks for confirming this! :+1: 

I've just filed feature request #59 so you may eventually specify the `ipv6_v6only` context option :+1:

**Comment by clue** [comment]
For the reference, #64 introduced the required socket context options, so you may want to check out the v0.4.6 release :+1:
