### ISSUE TITLE
SOCK_SEQPACKET support

### ISSUE THREAD

**Issue by jvwag** [reactphp/socket#73]
To refactor a current project with a SOCK_SEQPACKET unix domain socket I was seeking to use reactphp. This seemed impossible because the stream_socket_* functions does not support this type of socket (but lower level socket_* functions do).

The issue I'm facing is the event loop is using stream_select, which is incompatible with the resources created by socket_create (which i need to use for a SOCK_SEQPACKET socket).

I would like to write a solution for this in reactphp but I need some thoughts on design considerations:
- Should I need a SocketSelectLoop that runs alternating with the StreamSelectLoop? Is there a better way?
- Should I be pulling on php developers to enable SOCK_SEQPACKET in stream_socket_* functions?
- Even if php developers would implement this, would it be better to have a legacy implementation based on the low level socket_* functions?
- Where will this new reactphp socket type's source code reside? In the reactphp/socket codebase, or a new module?

Thank you for any thoughts on this.

With kind regards,
Joffrey

**Comment by clue** [comment]
Without going into too much detail, have you checked out https://github.com/clue/php-socket-react (a bit dated unfortunately)?

Technically, most other loop implemented should be able to handle socket resources just fine, so how about you give e.g. ext-ev a try? :+1:

**Comment by jvwag** [comment]
@clue I have not tried php-socket-react. Although it should work by adding some code to support the SEQPACKET socket type (a hybrid because it is connection based like a stream (requires accept(), but handles messages like a dgram socket (requires send/recv instead of read/write).

My current solution is deployed on a platform without eventlib based php extensions. This would be a good solution have stream_socket_* and socket_* connections to work in one loop. I will look into this.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:

If anybody feels like picking this up, PRs would be much appreciated :+1:
