### ISSUE TITLE
Handle stream_socket_get_name return "\0"

### ISSUE THREAD

**Issue by andig** [reactphp/socket#92]
https://github.com/reactphp/socket/blob/master/src/Connection.php#L44 should not only check for `false`but also for `"\0"` according to https://bugs.php.net/bug.php?id=74458.

Discovered through https://github.com/reactphp/http/pull/160#issuecomment-294438538. Since ratchet still uses 0.5 it would be great if this could also be back ported to 0.5...0.7.

**Comment by clue** [comment]
Thanks for spotting and filing both an upstream bug report and this issue!

This is something I've also spotted a couple of months ago when these methods have been added but didn't get to look into this in-depth. I agree that this is something that should be fixed (worked around) here and PRs would be much appreciated :+1: 

I'd like to address this in the master branch first and then check whether we should either backport this to previous release branches or (which I prefer) encourage consumers to upgrade to the latest version if this is reasonable :+1:

**Comment by andig** [comment]
I can add the PR for you and potentially even a test (need to check). I'd need it backported too since I'm using ppm and react/http and ratchet which forces me to stay on 0.5 for time being due to ratchet.

**Comment by andig** [comment]
No idea about the tests, sorry. If you want more PRs for the different branches please let me know.

**Comment by clue** [comment]
> I'd need it backported too since I'm using ppm and react/http and ratchet which forces me to stay on 0.5 for time being due to ratchet.

I've just updated https://github.com/ratchetphp/Ratchet/pull/485 to make sure Ratchet will also support Socket v0.7 and v0.6 :shipit:
